import headerSmall from './modules/headerSmall';
import headerSearch from './modules/headerSearch';
import navGlobal from './modules/navGlobal';
import footer from './modules/footer';
import navFavoriteSlider from './modules/navFavoriteSlider';
import marqueeSlider from './modules/marqueeSlider';
import countDown from './modules/countdown';
import productSlider from './modules/productSlider';
import productDetail from './modules/productDetail';
import btnShare from './modules/btnShare';
import listAccordion from './modules/listAccordion';
import selectReviewStars from './modules/selectReviewStars';
import form from './modules/form';
import { initDefaultModal, addToCartModal } from './modules/modal';
import { memberRankSlider } from './modules/member';

document.addEventListener('DOMContentLoaded', () => {
  headerSmall();
  headerSearch();
  navGlobal();
  footer();
  navFavoriteSlider();
  marqueeSlider();
  countDown();
  productSlider();
  productDetail();
  btnShare();
  listAccordion();
  selectReviewStars();
  form();
  initDefaultModal();
  addToCartModal();
  memberRankSlider();
});
